### ISSUE TITLE
API -> logout (strange error)

### ISSUE THREAD

**Issue by Julian-Cole** [scenaristeur/solidarity#1]
When I call sh.logout() I get a strange message,  the call itself works fine but I get a console error 
GET https://localhost/.well-known/solid/logout 404 (Not Found)

see pic

![image](https://user-images.githubusercontent.com/49248917/73611289-53d5e280-45d8-11ea-9126-d0d8be34d17d.png)

**Comment by scenaristeur** [comment]
it's a known non-blockante unresolved issue of solid-auth-client 
https://github.com/solid/solid-auth-client/issues/111
