### ISSUE TITLE
API -> getPhoto()

### ISSUE THREAD

**Issue by Julian-Cole** [scenaristeur/solidarity#2]
It would be good to have a getPhoto()  method which returned the uri of the profile picture.

**Comment by scenaristeur** [comment]
using Shighl ?   https://github.com/scenaristeur/shighl/blob/3ac5d143786e9cdde89539ca921a09c048f883d6/src/Shighl.js#L53

**Comment by Julian-Cole** [comment]
ah Perfect! thanks
