### ISSUE TITLE
UIX -> Send a long-chat message

### ISSUE THREAD

**Issue by Julian-Cole** [scenaristeur/solidarity#5]
Once the API is complete hook up the UI

**Comment by scenaristeur** [comment]
Send & reply are OK for me https://github.com/scenaristeur/shighl/issues/1
tested on https://scenaristeur.github.io/shighl/profile.html

![image](https://user-images.githubusercontent.com/4020744/74267016-8df46200-4d05-11ea-9cd5-3ca2acc8f8c7.png)

**Comment by Julian-Cole** [comment]
done!
