### ISSUE TITLE
Upload New Solidarity UI to GH-Pages

### ISSUE THREAD

**Issue by Julian-Cole** [scenaristeur/solidarity#7]

**Comment by scenaristeur** [comment]
first build the  /dist folder with 
```
npm run build

```
next update your fork of solidarity on github 
```
git status
git add .
git commit -m "a cool message to explain your commit"
git push
```
then your code must be updated on github.
You can then ask for a pull request to my repo, or push your dist folder to gh-pages 
with
 ```
git subtree push --prefix dist origin gh-pages
```
see 
https://stackoverflow.com/questions/36782467/set-subdirectory-as-website-root-on-github-pages
for how it works ;-)

**Comment by Julian-Cole** [comment]
thanks!
